---
- block:
  - name: mkdir directory
    file:
      path: ~/.cache/shell
      state: directory
  - name : touch chr file
    file:
      path: ~/.cache/shell/chpwd-recent-dirs
      state: touch
  tags:
    - zsh
