---
- block:
  - block:
    - name: mkdir directory
      file:
        path: ~/.cache/dein
        state: directory
    - name: install dein installer 
      get_url: 
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: ~/.cache/dein
        mode: 0755
    - name: Run installer.sh
      shell: ~/.cache/dein/installer.sh ~/.cache/dein/

  - block: 
    - name: make backup file
      file:
        path: ~/.vimbackup
        state: directory
  tags:
    - vim
