---
- block:
  - name: InitialKeyRepeat 
    osx_defaults:
      key: InitialKeyRepeat
      type: int
      value: 13
      state: present

  - name: KeyRepeat 
    osx_defaults:
      key: KeyRepeat
      type: int
      value: 1
      state: present

  - name: Dock autohide
    osx_defaults:
      domain: com.apple.dock
      key: autohide
      type: bool
      value: true
      state: present    

  - name: Make Dock small
    osx_defaults:
      domain: com.apple.dock
      key: tilesize
      type: float
      value: 20
      state: present

  - name: Show Dock delay
    osx_defaults:
      domain: com.apple.dock
      key: autohide-delay
      type: float 
      value: 20 
      state: present

  - name: Show hidden file on Finder
    osx_defaults:
      domain: com.apple.finder
      key: AppleShowAllFiles
      type: bool
      value: true
      state: present

  - name: Battery Showpercent
    osx_defaults:
      domain: com.apple.menuextra.battery
      key: ShowPercent
      type: string
      value: YES
      state: present

  - name: Disable Live convert
    osx_defaults:
      domain: com.apple.inputmethod.Kotoeri
      key: JIMPrefLiveConversionKey
      type: int
      value: 0
      state: present

  - name: Set Hot Corner As Screen Saver(corer)
    osx_defaults:
      domain: com.apple.dock
      key: wvous-tl-corner 
      type: int
      value: 5
      state: present

  - name: Set Hot Corner As Screen Saver(modifier)
    osx_defaults:
      domain: com.apple.dock
      key: wvous-tl-modifier 
      type: int
      value: 0
      state: present

  # - name: Require password back from screensaver
  #   osx_defaults:
  #     domain: com.apple.screensaver
  #     key: askForPassword 
  #     type: int
  #     value: 1
  #     state: present
  #
  # - name: Require password back from screensaver(Delay)
  #   osx_defaults:
  #     domain: com.apple.screensaver
  #     key: askForPasswordDelay 
  #     type: int
  #     value: 0
  #     state: present

  tags:
    - osx
